#!/usr/bin/env zsh

# MCP Starter Script - Zsh Version
# Configures Serena and Cipher MCP servers for Claude Code

setopt errexit
setopt nounset
setopt pipefail

# Color codes for output
autoload -U colors && colors

# Function to print colored output
print_color() {
    local message=$1
    local color=$2
    print -P "%F{$color}${message}%f"
}

# Function to check prerequisites
check_prerequisites() {
    local missing_deps=()
    
    for cmd in node npm python3 uv; do
        if ! command -v $cmd &>/dev/null; then
            missing_deps+=($cmd)
        fi
    done
    
    if [[ ${#missing_deps[@]} -ne 0 ]]; then
        print_color "Error: Missing required dependencies: ${missing_deps[*]}" "red"
        print_color "Please install the missing dependencies and try again." "yellow"
        exit 1
    fi
}

# Function to create project structure
create_project_structure() {
    local project_name=$1
    local project_path="${PWD}/${project_name}"
    
    if [[ -d "$project_path" ]]; then
        print_color "Warning: Project directory already exists: $project_path" "yellow"
        print -n "Do you want to continue? (y/n): "
        read -q REPLY
        echo
        if [[ "$REPLY" != "y" ]]; then
            print_color "Aborted." "red"
            exit 1
        fi
    else
        mkdir -p "$project_path"
    fi
    
    # Create required directories
    mkdir -p "${project_path}/.serena"
    mkdir -p "${project_path}/memAgent"
    
    echo "$project_path"
}

# Function to create Serena configuration
create_serena_config() {
    local project_path=$1
    local language=$2
    local config_file="${project_path}/.serena/project.yml"
    
    cat > "$config_file" << EOF
# Serena Project Configuration
# Generated by mcp-starter script

name: ${project_path:t}
language: ${language}
version: 1.0.0

# Project settings
settings:
  read_only: false
  auto_index: true
  enable_shell: true

# Language-specific settings
language_settings:
  primary_language: ${language}
  type_checking: true
  linting: true

# Tools configuration
tools:
  excluded_tools: []
  
# Memory settings
memories:
  enabled: true
  auto_save: true

# Context and modes
default_context: claude-code
default_modes:
  - interactive
  - editing

# Project metadata
metadata:
  created_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  created_by: mcp-starter
EOF
    
    print_color "Created Serena configuration: $config_file" "green"
}

# Function to create Cipher configuration
create_cipher_config() {
    local project_path=$1
    local config_file="${project_path}/memAgent/cipher.yml"
    
    cat > "$config_file" << 'EOF'
# Cipher Memory Agent Configuration
# Generated by mcp-starter script

# LLM Configuration
llm:
  provider: openai
  model: gpt-4-turbo
  apiKey: $OPENAI_API_KEY
  temperature: 0.7
  maxTokens: 4096

# Embedding Configuration
embedding:
  provider: openai
  model: text-embedding-3-small
  apiKey: $OPENAI_API_KEY
  dimensions: 1536

# System Prompt
systemPrompt: |
  You are an intelligent coding assistant with persistent memory capabilities.
  You help developers with code analysis, debugging, and implementation tasks.
  You maintain context across sessions and learn from previous interactions.

# Memory Configuration
memory:
  enabled: true
  type: persistent
  storage:
    type: local
    path: ./memory_store
  
# Vector Store Configuration
vectorStore:
  type: in-memory
  collection: project_memories

# Session Configuration
session:
  persistent: true
  autoSave: true
  saveInterval: 300 # seconds

# Tool Configuration
tools:
  enabled: true
  allowedTools:
    - cipher_memory_search
    - cipher_extract_and_operate_memory
    - cipher_add_memory
    - cipher_update_memory
    - cipher_delete_memory

# MCP Server Settings
mcp:
  mode: stdio
  strict: false
  timeout: 30000 # milliseconds

# Logging
logging:
  level: info
  file: ./logs/cipher.log
EOF
    
    print_color "Created Cipher configuration: $config_file" "green"
}

# Function to create .env file
create_env_file() {
    local project_path=$1
    local env_file="${project_path}/.env"
    
    if [[ -f "$env_file" ]]; then
        print_color "Warning: .env file already exists" "yellow"
        return
    fi
    
    cat > "$env_file" << 'EOF'
# Environment Variables for MCP Servers
# Generated by mcp-starter script

# OpenAI Configuration (Required for Cipher)
OPENAI_API_KEY=your-openai-api-key-here

# Optional: Additional API Keys
# ANTHROPIC_API_KEY=your-anthropic-api-key
# VOYAGE_API_KEY=your-voyage-api-key

# Cipher Configuration
CIPHER_LOG_LEVEL=info
NODE_ENV=development

# Vector Store Configuration (Optional)
# VECTOR_STORE_TYPE=qdrant
# VECTOR_STORE_URL=http://localhost:6333
# VECTOR_STORE_API_KEY=your-qdrant-api-key

# Workspace Memory (Optional)
USE_WORKSPACE_MEMORY=true
WORKSPACE_VECTOR_STORE_COLLECTION=workspace_memory
EOF
    
    print_color "Created .env file: $env_file" "green"
    print_color "IMPORTANT: Please update the OPENAI_API_KEY in the .env file" "yellow"
}

# Function to generate Claude Code MCP configuration
generate_claude_config() {
    local project_path=$1
    local language=$2
    local config_file="${project_path}/claude-mcp-config.json"
    
    cat > "$config_file" << EOF
{
  "mcpServers": {
    "serena": {
      "command": "uvx",
      "args": [
        "--from",
        "git+https://github.com/oraios/serena",
        "serena-mcp-server",
        "--context",
        "claude-code",
        "--project",
        "${project_path}",
        "--language",
        "${language}"
      ]
    },
    "cipher": {
      "type": "stdio",
      "command": "cipher",
      "args": [
        "--mode",
        "mcp",
        "--agent",
        "${project_path}/memAgent/cipher.yml"
      ],
      "env": {
        "OPENAI_API_KEY": "\${OPENAI_API_KEY}"
      }
    }
  }
}
EOF
    
    print_color "Generated Claude Code MCP configuration: $config_file" "green"
}

# Function to create setup instructions
create_setup_instructions() {
    local project_path=$1
    local instructions_file="${project_path}/MCP_SETUP_INSTRUCTIONS.md"
    
    cat > "$instructions_file" << 'EOF'
# MCP Server Setup Instructions

## Prerequisites Checklist

1. **Environment Variables**
   - [ ] Update `OPENAI_API_KEY` in `.env` file

2. **Install Dependencies**
   ```bash
   # Install Cipher globally
   npm install -g @byterover/cipher
   
   # Install uv (Python package manager) if not already installed
   curl -LsSf https://astral.sh/uv/install.sh | sh
   ```

## Claude Code Configuration

1. **Add MCP servers to Claude Code**:
   ```bash
   # From the project directory, run:
   claude mcp add serena -- uvx --from git+https://github.com/oraios/serena serena-mcp-server --context claude-code --project $(pwd)
   claude mcp add cipher -- cipher --mode mcp --agent $(pwd)/memAgent/cipher.yml
   ```

2. **Start Claude Code**:
   ```bash
   claude
   ```

3. **Initialize Serena** (in Claude Code chat):
   ```
   /mcp__serena__initial_instructions
   ```

## Verification

1. Check that both MCP servers are running:
   - Look for the hammer icon in Claude Code
   - Available tools should include both Serena and Cipher tools

2. Test Serena:
   ```
   "Show me the project structure"
   ```

3. Test Cipher:
   ```
   "Remember that this project uses [your framework/language]"
   ```

## Troubleshooting

- **Serena not responding**: Check if language servers are installed for your chosen language
- **Cipher memory errors**: Verify OPENAI_API_KEY is set correctly
- **Connection issues**: Restart Claude Code and check logs
EOF
    
    print_color "Created setup instructions: $instructions_file" "green"
}

# Main function
main() {
    print_color "MCP Starter - Zsh Version" "blue"
    print_color "============================" "blue"
    
    # Check arguments
    if [[ $# -lt 1 ]]; then
        print_color "Usage: $0 <project_name> [language]" "red"
        print_color "Example: $0 my-project typescript" "yellow"
        exit 1
    fi
    
    local project_name=$1
    local language=${2:-typescript}
    
    # Validate language
    local valid_languages=(typescript javascript python java go rust php elixir clojure c cpp)
    if [[ ! ${valid_languages[(r)$language]} ]]; then
        print_color "Warning: Unsupported language '${language}'. Using 'typescript' instead." "yellow"
        language="typescript"
    fi
    
    print_color "Project: $project_name" "green"
    print_color "Language: $language" "green"
    echo
    
    # Check prerequisites
    print_color "Checking prerequisites..." "blue"
    check_prerequisites
    
    # Create project structure
    print_color "Creating project structure..." "blue"
    project_path=$(create_project_structure "$project_name")
    
    # Create configuration files
    print_color "Creating configuration files..." "blue"
    create_serena_config "$project_path" "$language"
    create_cipher_config "$project_path"
    create_env_file "$project_path"
    generate_claude_config "$project_path" "$language"
    create_setup_instructions "$project_path"
    
    echo
    print_color "✅ MCP server configuration completed successfully!" "green"
    echo
    print_color "Next steps:" "blue"
    print_color "1. Navigate to project: cd $project_name" "yellow"
    print_color "2. Update OPENAI_API_KEY in .env file" "yellow"
    print_color "3. Follow instructions in MCP_SETUP_INSTRUCTIONS.md" "yellow"
    echo
    print_color "Happy coding with Claude Code + Serena + Cipher! 🚀" "blue"
}

# Run main function
main "$@"